# Generated by Django 3.2.5 on 2021-07-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
