# Generated by Django 3.2.5 on 2021-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0002_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
