# Generated by Django 3.2.5 on 2021-07-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0002_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='This is Description', max_length=255),
        ),
    ]
