# Generated by Django 3.2.5 on 2021-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphicdesignapp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=80)),
            ],
        ),
    ]
