# Generated by Django 3.2.5 on 2021-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0003_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
