# Generated by Django 3.2.5 on 2021-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0004_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
