# Generated by Django 3.2.5 on 2021-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0005_design_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
