# Generated by Django 3.2.5 on 2021-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesignapp', '0006_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
